### PR TITLE
Colorize the output

### PR DESCRIPTION
**Pull request by erogleva**
license-checker colorizes the name and version of the dependencies when printing the output to the terminal, which makes it slightly better readable. So I thought that it would maybe be a good idea to do the same here :)

### CODE REVIEW

**Comment by mwittig** [comment]
Thank you very much for your contribution! Colorized output is definitely an improvement if it is display console. However, as some users may redirect the output, the output may contain disturbing control codes in the case. I am not sure whether `chalk` auto-detection can cover all cases. I'll need to have a look at this. Apart from this, the "--no-color" option should be documented as some user may not be aware of this

**Comment by erogleva** [comment]
Thank you for your feedback! I have added and documented the noColor option. As for the redirection, it really seems that it doesn't work in all cases  with the colors, I will look again into this too.

**Comment by mwittig** [comment]
Excellent. Note, however, the `chalk` has a built-in handling for 'no-color' as far as I know. Well, I need to test this myself. Let me sort this out for and I keep you posted here.

**Comment by erogleva** [comment]
Ah okay, thanks, I hadn't seen this! I've now removed the additional option.

**Comment by mwittig** [comment]
Excellent. Thanks again for your contribution. Much appreciated!

**Pull request merged**
